version: '3'

services:
  arm-mensch-maschine-worker:
    build:
      context: ../mensch-maschine-worker/.
      dockerfile: ../mensch-maschine-worker/docker/Dockerfile.arm
    ports:
      - "8080:8080"

# services:
#   arm-mensch-maschine-worker:
#     build:
#       context: ../mensch-maschine-worker/.
#       dockerfile: ../mensch-maschine-worker/docker/Dockerfile.arm
#     networks:
#       - arm-backend

#   arm-mensch-maschine-db:
#     build:
#       context: ../mensch-maschine-db/.
#       dockerfile: ../mensch-maschine-db/docker/Dockerfile.arm
#     networks:
#       - arm-backend
#     volumes:
#       - arm-db-data:/var/lib/postgresql/data

#   arm-mensch-maschine-api:
#     build:
#       context: ../mensch-maschine-api/.
#       dockerfile: ../mensch-maschine-api/docker/Dockerfile.arm
#     networks:
#       - arm-backend
#       - arm-frontend

#   arm-mensch-maschine-webapp:
#     build:
#       context: ../mensch-maschine-webapp/.
#       dockerfile: ../mensch-maschine-webapp/docker/Dockerfile.arm
#     networks:
#       - arm-frontend
#     ports:
#       - "80:80"

# networks:
#   arm-backend:
#   arm-frontend:

# volumes:
#   arm-db-data:
